// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// LoSCpp
std::vector<int> LoSCpp(const IntegerMatrix rc1, const int r0, const int c0, const double observerHeight, const NumericMatrix dsm_mat);
RcppExport SEXP _GVI_LoSCpp(SEXP rc1SEXP, SEXP r0SEXP, SEXP c0SEXP, SEXP observerHeightSEXP, SEXP dsm_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type rc1(rc1SEXP);
    Rcpp::traits::input_parameter< const int >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< const int >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const double >::type observerHeight(observerHeightSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type dsm_mat(dsm_matSEXP);
    rcpp_result_gen = Rcpp::wrap(LoSCpp(rc1, r0, c0, observerHeight, dsm_mat));
    return rcpp_result_gen;
END_RCPP
}
// countGroups
List countGroups(IntegerMatrix xyVisible, IntegerVector uniqueXY);
RcppExport SEXP _GVI_countGroups(SEXP xyVisibleSEXP, SEXP uniqueXYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type xyVisible(xyVisibleSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type uniqueXY(uniqueXYSEXP);
    rcpp_result_gen = Rcpp::wrap(countGroups(xyVisible, uniqueXY));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GVI_LoSCpp", (DL_FUNC) &_GVI_LoSCpp, 5},
    {"_GVI_countGroups", (DL_FUNC) &_GVI_countGroups, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_GVI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
