# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bresenham <- function(x1, y1, x2, y2) {
    .Call(`_GVI_bresenham`, x1, y1, x2, y2)
}

countGroups <- function(xyVisible, uniqueXY) {
    .Call(`_GVI_countGroups`, xyVisible, uniqueXY)
}

isVisible <- function(x) {
    .Call(`_GVI_isVisible`, x)
}

tangents <- function(x1, y1, height0, xy2, dsm_profile) {
    .Call(`_GVI_tangents`, x1, y1, height0, xy2, dsm_profile)
}

