# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Line of Sight
#' @description Computes a single Line of Sight (LoS) using a Digital Surface Model (DSM) matrix. Uses a C++ implementation of Bresenham's line algorithm.
#'
#' @param rc1 integer matrix; Row and column of the targets location in the DSM matrix.
#' @param r0 integer; Specifying the row of the starting location in the DSM matrix.
#' @param c0 integer; Specifying the column of the starting location in the DSM matrix.
#' @param observerHeight numeric > 0; Height of the observer (e.g. 1.7).
#' @param dsm_mat numeric matrix; Matrix derived from a DSM.
#'
#' @return Cell numbers of all visible cells of the DSM along the line. 
#' 
#' @export
LoSCpp <- function(rc1, r0, c0, observerHeight, dsm_mat) {
    .Call(`_GVI_LoSCpp`, rc1, r0, c0, observerHeight, dsm_mat)
}

countGroups <- function(xyVisible, uniqueXY) {
    .Call(`_GVI_countGroups`, xyVisible, uniqueXY)
}

